server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huike?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Abcd@mysql171
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    password: Abcd@redis171
    host: 127.0.0.1

logging:
  level:
    org:
      springframework:
        security: DEBUG


token:
  header: Authorization
  secret: huike-crm-secret-Abcd@jwt171
  expiration: 180 # minute

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl